# Generated by Django 5.0.6 on 2024-06-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedToken',
        ),
    ]
