# Generated by Django 5.0.6 on 2024-06-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('myapi', '0002_delete_extendedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('isdeleted', models.BooleanField(default=False)),
            ],
            bases=('authtoken.token',),
        ),
    ]
