# Generated by Django 5.0.6 on 2024-06-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('myapi', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='MyapiToken',
        ),
    ]
